### ISSUE TITLE
Translation status

### ISSUE THREAD

**Issue by Leronez** [translation-ru/pinia#1]
## Status of translation by pages

- [x] vitepress config
- [x]  main page and menu
- [x] Introduction
  - [x] What is Pinia? (/introduction.md)
  - [x] Getting Started (/getting-started.md)
- [x] Core Concepts
  - [x] Defining a Store (/core-concepts/index.md)
  - [x] State (/core-concepts/state.md)
  - [x] Getters (/core-concepts/getters.md)
  - [x] Actions (/core-concepts/actions.md)
  - [x] Plugins (/core-concepts/plugins.md)
  - [x] Stores outside of components (/core-concepts/outside-component-usage.md)
- [x] Server-Side Rendering (SSR)
  - [x] Vue and Vite (/ssr/index.md)
  - [x] Nuxt.js (/ssr/nuxt.md)
- [x] Cookbook
  - [x] Index (cookbook/index.md)
  - [x] **(assigned to @Leronez)** #2 
  - [x] **(assigned to @Leronez)** #3
  - [x] **(assigned to @Leronez)** #4
  - [x] **(assigned to @Leronez)** #5
  - [x] **(assigned to @Leronez)**  #6
  - [x]  **(assigned to @Leronez)** #7
  - [x]  **(assigned to @Leronez)**  #8
  - [x] **(assigned to @Leronez)**  #9
- [x] API
  - [x] **(assigned to @Leronez)** #10
  - [x] **(assigned to @Leronez)** #11
  - [x] **(assigned to @Leronez)** #12
  - [x] **(assigned to @Leronez)** #13
  - [x] **(assigned to @Leronez)** #14
  - [x] **(assigned to @Leronez)** #15
  - [x] **(assigned to @Leronez)** #16
  - [x] **(assigned to @Leronez)** #17
  - [x] **(assigned to @Leronez)** #18
  - [x] **(assigned to @Leronez)** #19
  - [x] **(assigned to @Leronez)** #20
  - [x] **(assigned to @Leronez)** #21
  - [x] **(assigned to @Leronez)** #22
  - [x] **(assigned to @Leronez)** #23
  - [x] **(assigned to @Leronez)** #24
  - [x] **(assigned to @Leronez)** #25
  - [x] **(assigned to @Leronez)** #26
  - [x] **(assigned to @Leronez)** #27
  - [x] **(assigned to @Leronez)** #35
  - [x] **(assigned to @Leronez)** #34
  - [x] **(assigned to @Leronez)** #33
  - [x] **(assigned to @Leronez)** #32
  - [x] **(assigned to @Leronez)** #31
  - [x] **(assigned to @Leronez)** #30
  - [x] **(assigned to @Leronez)** #29
  - [x] **(assigned to @Leronez)** #28

**Comment by Leronez** [comment]
Для того, чтобы взять страницу в работу по переводу, напишите в соответствующем issue об этом. Кто-то из мейнтейнеров закрепит задачу за вами, и укажет об этом в текущем issue.
